"""initial schema

Revision ID: 20260805_01
Revises:
Create Date: 2026-08-05 01:38:39.723251
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260805_01"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "configs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("scope", sa.String(), nullable=False),
        sa.Column("scope_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("agent_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("credential_key", sa.String(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("kind", "scope", "scope_id", "name"),
    )
    op.create_index(op.f("ix_configs_agent_id"), "configs", ["agent_id"], unique=False)
    op.create_index(op.f("ix_configs_credential_key"), "configs", ["credential_key"], unique=False)
    op.create_index(op.f("ix_configs_kind"), "configs", ["kind"], unique=False)
    op.create_index(op.f("ix_configs_scope"), "configs", ["scope"], unique=False)
    op.create_index(op.f("ix_configs_scope_id"), "configs", ["scope_id"], unique=False)
    op.create_index(op.f("ix_configs_user_id"), "configs", ["user_id"], unique=False)
    op.create_table(
        "import_runs",
        sa.Column("source_sha256", sa.String(), nullable=False),
        sa.Column("source_path", sa.Text(), nullable=False),
        sa.Column("imported_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("report", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("source_sha256"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "agents",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_agents_is_public"), "agents", ["is_public"], unique=False)
    op.create_index(op.f("ix_agents_user_id"), "agents", ["user_id"], unique=False)
    op.create_table(
        "apikeys",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("key_hash", sa.String(), nullable=False),
        sa.Column("key_prefix", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_apikeys_key_hash"), "apikeys", ["key_hash"], unique=True)
    op.create_index(op.f("ix_apikeys_type"), "apikeys", ["type"], unique=False)
    op.create_index(op.f("ix_apikeys_user_id"), "apikeys", ["user_id"], unique=False)
    op.create_table(
        "web_sessions",
        sa.Column("sid", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("sid"),
    )
    op.create_index(
        op.f("ix_web_sessions_expires_at"), "web_sessions", ["expires_at"], unique=False
    )
    op.create_index(op.f("ix_web_sessions_user_id"), "web_sessions", ["user_id"], unique=False)
    op.create_table(
        "agent_files",
        sa.Column("agent_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("data", sa.LargeBinary(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("agent_id", "user_id", "filename"),
    )
    op.create_table(
        "apikey_agents",
        sa.Column("apikey_id", sa.String(), nullable=False),
        sa.Column("agent_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["apikey_id"], ["apikeys.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("apikey_id", "agent_id"),
    )
    op.create_index(op.f("ix_apikey_agents_agent_id"), "apikey_agents", ["agent_id"], unique=False)
    op.create_table(
        "cron_jobs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("agent_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("schedule", sa.String(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("channel", sa.String(), nullable=False),
        sa.Column("chat_id", sa.String(), nullable=False),
        sa.Column("account_id", sa.String(), nullable=False),
        sa.Column("timezone", sa.String(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("last_run", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_run", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cron_jobs_agent_id"), "cron_jobs", ["agent_id"], unique=False)
    op.create_index(op.f("ix_cron_jobs_enabled"), "cron_jobs", ["enabled"], unique=False)
    op.create_index(op.f("ix_cron_jobs_user_id"), "cron_jobs", ["user_id"], unique=False)
    op.create_table(
        "sessions",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("agent_id", sa.String(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("channel", sa.String(), nullable=False),
        sa.Column("account_id", sa.String(), nullable=False),
        sa.Column("chat_id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("messages", sa.JSON(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("message_count", sa.Integer(), nullable=False),
        sa.Column("chatter_user_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "agent_id", "key"),
    )
    op.create_index(op.f("ix_sessions_updated_at"), "sessions", ["updated_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sessions_updated_at"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(op.f("ix_cron_jobs_user_id"), table_name="cron_jobs")
    op.drop_index(op.f("ix_cron_jobs_enabled"), table_name="cron_jobs")
    op.drop_index(op.f("ix_cron_jobs_agent_id"), table_name="cron_jobs")
    op.drop_table("cron_jobs")
    op.drop_index(op.f("ix_apikey_agents_agent_id"), table_name="apikey_agents")
    op.drop_table("apikey_agents")
    op.drop_table("agent_files")
    op.drop_index(op.f("ix_web_sessions_user_id"), table_name="web_sessions")
    op.drop_index(op.f("ix_web_sessions_expires_at"), table_name="web_sessions")
    op.drop_table("web_sessions")
    op.drop_index(op.f("ix_apikeys_user_id"), table_name="apikeys")
    op.drop_index(op.f("ix_apikeys_type"), table_name="apikeys")
    op.drop_index(op.f("ix_apikeys_key_hash"), table_name="apikeys")
    op.drop_table("apikeys")
    op.drop_index(op.f("ix_agents_user_id"), table_name="agents")
    op.drop_index(op.f("ix_agents_is_public"), table_name="agents")
    op.drop_table("agents")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("import_runs")
    op.drop_index(op.f("ix_configs_user_id"), table_name="configs")
    op.drop_index(op.f("ix_configs_scope_id"), table_name="configs")
    op.drop_index(op.f("ix_configs_scope"), table_name="configs")
    op.drop_index(op.f("ix_configs_kind"), table_name="configs")
    op.drop_index(op.f("ix_configs_credential_key"), table_name="configs")
    op.drop_index(op.f("ix_configs_agent_id"), table_name="configs")
    op.drop_table("configs")
    # ### end Alembic commands ###
